name: Publish package to GitHub Packages
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Setup Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}